"""Official Zalo Bot contracts and code-only webhook helpers."""

from legal_chatbot.channels.auth import (
    AUTH_FAILURE_RESPONSE,
    AUTH_FAILURE_RESPONSE_BODY,
    BODY_TOO_LARGE_RESPONSE,
    BODY_TOO_LARGE_RESPONSE_BODY,
    BOT_SECRET_HEADER,
    CHANNEL_JSON_MEDIA_TYPE,
    ChannelAuthFailureResponse,
    delivery_hmac,
    identity_hmac,
    verify_bot_secret,
)
from legal_chatbot.channels.config import ChannelSettings
from legal_chatbot.channels.errors import ChannelError, ChannelErrorCode
from legal_chatbot.channels.models import (
    BINDING_LEASE_SECONDS,
    HMAC_HEX_LENGTH,
    INBOUND_TEXT_MAX_CHARS,
    MAX_BODY_BYTES,
    OUTBOUND_MAX_ATTEMPTS,
    OUTBOUND_TEXT_MAX_CHARS,
    ChannelBindingReservation,
    ChannelBindingReservationStatus,
    ChannelBindingStatus,
    ChannelDeliveryReceipt,
    ChannelDeliveryReceiptStatus,
    ChannelInboundMessage,
    ChannelIngressReceipt,
    ChannelIngressStatus,
    ChannelKind,
    ChannelOutboundMessage,
    ChannelOutboundReservation,
    ChannelOutboundReservationStatus,
    ChannelOutboundStatus,
)
from legal_chatbot.channels.recipients import OfficialBotRecipientRegistry

__all__ = [
    "AUTH_FAILURE_RESPONSE",
    "AUTH_FAILURE_RESPONSE_BODY",
    "BINDING_LEASE_SECONDS",
    "BODY_TOO_LARGE_RESPONSE",
    "BODY_TOO_LARGE_RESPONSE_BODY",
    "BOT_SECRET_HEADER",
    "CHANNEL_JSON_MEDIA_TYPE",
    "ChannelAuthFailureResponse",
    "ChannelBindingReservation",
    "ChannelBindingReservationStatus",
    "ChannelBindingStatus",
    "ChannelDeliveryReceipt",
    "ChannelDeliveryReceiptStatus",
    "ChannelError",
    "ChannelErrorCode",
    "ChannelInboundMessage",
    "ChannelIngressReceipt",
    "ChannelIngressStatus",
    "ChannelKind",
    "ChannelOutboundMessage",
    "ChannelOutboundReservation",
    "ChannelOutboundReservationStatus",
    "ChannelOutboundStatus",
    "ChannelSettings",
    "HMAC_HEX_LENGTH",
    "INBOUND_TEXT_MAX_CHARS",
    "MAX_BODY_BYTES",
    "OUTBOUND_MAX_ATTEMPTS",
    "OUTBOUND_TEXT_MAX_CHARS",
    "OfficialBotRecipientRegistry",
    "delivery_hmac",
    "identity_hmac",
    "verify_bot_secret",
]
