"""Pure domain contracts for the legal-evidence investigation pipeline."""

from .compatibility import map_legacy_authority_role, map_legacy_coverage_state
from .context import create_legal_case
from .models import (
    AnalysisOrigin,
    AnalyzerOutcome,
    AnswerDraft,
    ApplicabilityState,
    AuthorityCandidate,
    AuthorityFamily,
    AuthorityRole,
    AuthorityState,
    CandidateDocument,
    CaseStage,
    CoverageEntry,
    CoverageMatrix,
    CoverageState,
    DocumentVersionReference,
    EvidenceReference,
    EvidenceUnit,
    LegalCaseContext,
    LegalQuestionAnalysisResult,
    LegalTruthCategory,
    PreferredSourceTier,
    QuestionAnalysis,
    RelationHint,
    RelationType,
    RelationVerification,
    ReviewDecision,
    ReviewResult,
    SubIntent,
    VerifiedRelation,
)
from .ports import LegalEvidenceInvestigationPort, LegalQuestionAnalyzerPort
from .transitions import (
    LegalCaseTransitionError,
    advance_case,
    record_reviewed_relation,
    verified_applicability_state,
    verify_relation,
)

__all__ = [
    "AnalysisOrigin",
    "AnalyzerOutcome",
    "AnswerDraft",
    "ApplicabilityState",
    "AuthorityCandidate",
    "AuthorityFamily",
    "AuthorityRole",
    "AuthorityState",
    "CandidateDocument",
    "CaseStage",
    "CoverageEntry",
    "CoverageMatrix",
    "CoverageState",
    "DocumentVersionReference",
    "EvidenceReference",
    "EvidenceUnit",
    "LegalCaseContext",
    "LegalQuestionAnalysisResult",
    "LegalCaseTransitionError",
    "LegalEvidenceInvestigationPort",
    "LegalQuestionAnalyzerPort",
    "LegalTruthCategory",
    "QuestionAnalysis",
    "PreferredSourceTier",
    "RelationHint",
    "RelationType",
    "RelationVerification",
    "ReviewDecision",
    "ReviewResult",
    "SubIntent",
    "VerifiedRelation",
    "advance_case",
    "create_legal_case",
    "map_legacy_authority_role",
    "map_legacy_coverage_state",
    "record_reviewed_relation",
    "verified_applicability_state",
    "verify_relation",
]
