"""Pure M07 conversation contracts, policy helpers, and repository seams."""

from legal_chatbot.chat.models import (
    CONVERSATION_CONTEXT_MAX_CHARS,
    CONVERSATION_CONTEXT_TURN_LIMIT,
)
from legal_chatbot.conversation.config import ConversationSettings
from legal_chatbot.conversation.errors import ConversationError, ConversationErrorCode
from legal_chatbot.conversation.models import (
    ACTIVE_TOPIC_MAX_CHARS,
    ASSISTANT_TEXT_MAX_CHARS,
    DELIVERY_ID_MAX_CHARS,
    PROCESSING_LEASE_SECONDS,
    REFERENCE_LIMIT_PER_KIND,
    RETAINED_EXCHANGE_LIMIT,
    RETENTION_SECONDS,
    ROLLING_SUMMARY_MAX_CHARS,
    USER_TEXT_MAX_CHARS,
    ConversationCompactionCandidate,
    ConversationCompactionPlan,
    ConversationExchangeStatus,
    ConversationReference,
    ConversationReferenceKind,
    ConversationRequest,
    ConversationReservation,
    ConversationReservationResult,
    ConversationReservationStatus,
    ConversationResult,
    ConversationStateSnapshot,
    ConversationStateUpdate,
    ConversationTurn,
    ConversationTurnRole,
    CreateConversationResult,
    PersistedConversationExchange,
)
from legal_chatbot.conversation.policy import (
    delivery_key_sha256,
    derive_retrieval_query,
    normalize_delivery_id,
    to_chat_context,
)
from legal_chatbot.conversation.port import ConversationRepositoryPort, GroundedChatPort

__all__ = [
    "ACTIVE_TOPIC_MAX_CHARS",
    "ASSISTANT_TEXT_MAX_CHARS",
    "CONVERSATION_CONTEXT_MAX_CHARS",
    "CONVERSATION_CONTEXT_TURN_LIMIT",
    "DELIVERY_ID_MAX_CHARS",
    "PROCESSING_LEASE_SECONDS",
    "REFERENCE_LIMIT_PER_KIND",
    "RETAINED_EXCHANGE_LIMIT",
    "RETENTION_SECONDS",
    "ROLLING_SUMMARY_MAX_CHARS",
    "USER_TEXT_MAX_CHARS",
    "ConversationError",
    "ConversationErrorCode",
    "ConversationCompactionCandidate",
    "ConversationCompactionPlan",
    "ConversationExchangeStatus",
    "ConversationReference",
    "ConversationReferenceKind",
    "ConversationRequest",
    "ConversationReservation",
    "ConversationReservationResult",
    "ConversationReservationStatus",
    "ConversationResult",
    "ConversationRepositoryPort",
    "ConversationSettings",
    "ConversationStateSnapshot",
    "ConversationStateUpdate",
    "ConversationTurn",
    "ConversationTurnRole",
    "CreateConversationResult",
    "GroundedChatPort",
    "PersistedConversationExchange",
    "delivery_key_sha256",
    "derive_retrieval_query",
    "normalize_delivery_id",
    "to_chat_context",
]
