"""Pure M06 Phase 1 grounded-chat contracts and deterministic policy helpers."""

from legal_chatbot.chat.config import ChatSettings
from legal_chatbot.chat.errors import ChatError, ChatErrorCode
from legal_chatbot.chat.models import (
    ANSWER_MAX_CHARS,
    CONVERSATION_CONTEXT_MAX_CHARS,
    CONVERSATION_CONTEXT_TURN_LIMIT,
    DEFAULT_MAX_CITATIONS,
    EXCERPT_MAX_CHARS,
    MAX_CITATIONS,
    MAX_OUTPUT_TOKENS,
    PROMPT_MAX_CHARS,
    QUESTION_MAX_CHARS,
    TOTAL_EVIDENCE_MAX_CHARS,
    ChatOutcome,
    ChatPolicyDecision,
    ChatReasonCode,
    ChatRequest,
    ConversationContext,
    ConversationContextTurn,
    GroundedChatResult,
    GroundingEvidence,
    GroundingEvidenceRequest,
    GroundingExcerpt,
    ProviderAnswer,
)
from legal_chatbot.chat.planner_models import (
    PLANNER_MAX_EXPANSION_TERMS,
    PLANNER_MAX_INPUT_CHARS,
    PLANNER_MAX_OUTPUT_TOKENS,
    PLANNER_MAX_PHRASES,
    QueryPlannerOutcome,
    QueryPlannerPlan,
    QueryPlannerResult,
)
from legal_chatbot.chat.planner_parser import StrictQueryPlannerParser
from legal_chatbot.chat.planner_prompt import build_query_planner_prompt
from legal_chatbot.chat.planner_service import LLMQueryPlanner
from legal_chatbot.chat.policy import (
    AS_OF_PHRASES,
    CURRENT_EFFECT_PHRASES,
    GENERIC_REFUSAL_TEXT,
    NO_RESULTS_CLARIFICATION_TEXT,
    TEMPORAL_REFUSAL_TEXT,
    apply_temporal_guard,
    effective_temporal_scope,
    refusal_decision,
    retrieval_policy_decision,
)
from legal_chatbot.chat.port import (
    CanonicalAnchorResolverPort,
    GroundingEvidencePort,
    ProviderOutputParserPort,
    QueryPlannerPort,
    RetrievalPort,
)
from legal_chatbot.chat.service import GroundedChatService, validate_chat_provider_compatibility

__all__ = [
    "ANSWER_MAX_CHARS",
    "AS_OF_PHRASES",
    "CURRENT_EFFECT_PHRASES",
    "CanonicalAnchorResolverPort",
    "ChatError",
    "ChatErrorCode",
    "ChatOutcome",
    "ChatPolicyDecision",
    "ChatReasonCode",
    "ChatRequest",
    "ChatSettings",
    "CONVERSATION_CONTEXT_MAX_CHARS",
    "CONVERSATION_CONTEXT_TURN_LIMIT",
    "DEFAULT_MAX_CITATIONS",
    "ConversationContext",
    "ConversationContextTurn",
    "EXCERPT_MAX_CHARS",
    "GENERIC_REFUSAL_TEXT",
    "GroundedChatResult",
    "GroundedChatService",
    "GroundingEvidence",
    "GroundingEvidencePort",
    "GroundingEvidenceRequest",
    "GroundingExcerpt",
    "MAX_CITATIONS",
    "MAX_OUTPUT_TOKENS",
    "PLANNER_MAX_EXPANSION_TERMS",
    "PLANNER_MAX_INPUT_CHARS",
    "PLANNER_MAX_OUTPUT_TOKENS",
    "PLANNER_MAX_PHRASES",
    "NO_RESULTS_CLARIFICATION_TEXT",
    "PROMPT_MAX_CHARS",
    "ProviderAnswer",
    "ProviderOutputParserPort",
    "QueryPlannerOutcome",
    "QueryPlannerPlan",
    "QueryPlannerPort",
    "QueryPlannerResult",
    "QUESTION_MAX_CHARS",
    "RetrievalPort",
    "TEMPORAL_REFUSAL_TEXT",
    "TOTAL_EVIDENCE_MAX_CHARS",
    "StrictQueryPlannerParser",
    "LLMQueryPlanner",
    "apply_temporal_guard",
    "build_query_planner_prompt",
    "effective_temporal_scope",
    "refusal_decision",
    "retrieval_policy_decision",
    "validate_chat_provider_compatibility",
]
